TauTriggerBarrel_90perc:
  sample: VBFHToTauTau
  default_version: V30
  reference_object:
    object: "part_tau"
    suffix: "Pt"
    label: "Gen Taus"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    nnTau:
      suffix: "Pt"
      label: "NN Tau"
      cuts:
        - "abs({eta}) < 2.4"
        - "{passloosenn}==1"
      match_dR: 0.1
    caloTau:
      suffix: "Pt"
      label: "Calo Tau"
      cuts:
        - "abs({eta}) < 2.4"
      match_dR: 0.3
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (barrel, L1 $p_T > <threshold>$ GeV)"
  thresholds: [20, 30]
  scalings:
    method: "naive"
    threshold: 0.90
  binning:
    min: 0
    max: 150
    step: 6

TauTriggerEndcap_90perc:
  sample: VBFHToTauTau
  default_version: V30
  reference_object:
    object: "part_tau"
    suffix: "Pt"
    label: "Gen Taus"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    nnTau:
      suffix: "Pt"
      label: "NN Tau"
      cuts:
        - "abs({eta}) < 2.4"
        - "{passloosenn}==1"
      match_dR: 0.1
    caloTau:
      suffix: "Pt"
      label: "Calo Tau"
      cuts:
        - "abs({eta}) < 2.4"
      match_dR: 0.3
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (endcap, L1 $p_T > <threshold>$ GeV)"
  thresholds: [20, 30]
  scalings:
    method: "naive"
    threshold: 0.90
  binning:
    min: 0
    max: 150
    step: 6

TauTriggerBarrel_50perc:
  sample: VBFHToTauTau
  default_version: V30
  reference_object:
    object: "part_tau"
    suffix: "Pt"
    label: "Gen Taus"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    nnTau:
      suffix: "Pt"
      label: "NN Tau"
      cuts:
        - "abs({eta}) < 2.4"
        - "{passloosenn}==1"
      match_dR: 0.1
    caloTau:
      suffix: "Pt"
      label: "Calo Tau"
      cuts:
        - "abs({eta}) < 2.4"
      match_dR: 0.3
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (barrel, L1 $p_T > <threshold>$ GeV)"
  thresholds: [20, 30]
  scalings:
    method: "naive"
    threshold: 0.50
  binning:
    min: 0
    max: 150
    step: 6

TauTriggerEndcap_50perc:
  sample: VBFHToTauTau
  default_version: V30
  reference_object:
    object: "part_tau"
    suffix: "Pt"
    label: "Gen Taus"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    nnTau:
      suffix: "Pt"
      label: "NN Tau"
      cuts:
        - "abs({eta}) < 2.4"
        - "{passloosenn}==1"
      match_dR: 0.1
    caloTau:
      suffix: "Pt"
      label: "Calo Tau"
      cuts:
        - "abs({eta}) < 2.4"
      match_dR: 0.3
  xlabel: "Gen. pT (GeV)"
  ylabel: "Trigger Efficiency (endcap, L1 $p_T > <threshold>$ GeV)"
  thresholds: [20, 30]
  scalings:
    method: "naive"
    threshold: 0.50
  binning:
    min: 0
    max: 150
    step: 6
