ElectronsMatchingBarrel:
  sample: Zee
  default_version: V26
  reference_object:
    object: "part_e"
    suffix: "Pt"
    label: "Gen Electrons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    EG:
      suffix: "Pt"
      label: "EG Electron"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.4"
      #  - "{passeseleid} == 1"
    tkElectron:
      suffix: "Pt"
      label: "TkElectron"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 2.4"
        - "{passeseleid} == 1"
    #tkElectronIso:
    #  suffix: "Pt"
    #  label: "TkElectron Iso"
    #  iso_BB: 0.13
    #  iso_EE: 0.28
    #  iso_branch: "trkiso"
    #  quality_id: "QUAL_BarrelNoneEndcap3"
    #  cuts:
    #    - "abs({eta}) < 2.4"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  binning:
    min: 0
    max: 150
    step: 3

ElectronsMatchingEndcap:
  sample: Zee
  default_version: V26
  reference_object:
    object: "part_e"
    suffix: "Pt"
    label: "Gen Electrons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    EG:
      suffix: "Pt"
      label: "EG Electron"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 2.4"
      #  - "{passessaid} == 1"
    tkElectron:
      suffix: "Pt"
      label: "TkElectron"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 2.4"
        - "{passeseleid} == 1"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Endcap)"
  binning:
    min: 0
    max: 150
    step: 3
