outdir: "/eos/user/d/dhundhau/www"

V22:
  DY: "/eos/cms/store/cmst3/group/l1tr/phase2Menu/EmuDev/DYToLL_M-50_TuneCP5_14TeV-pythia8/DY_PU200_v22/220407_094155/0000//"
  TT:
    ntuple_path: "/eos/cms/store/cmst3/group/l1tr/phase2Menu/EmuDev/TT_TuneCP5_14TeV-powheg-pythia8/TT_PU200_v22/220407_094308/0000//"
    gen_trees:
      genMetTrue: {operation: "copy", treeKey: "genMetTrue"}
      genJetPt: {operation: "copy", treeKey: "jetPt"}
      genJetEta: {operation: "copy", treeKey: "jetEta"}
      genHT: {operation: "sumThreshold30", treeKey: "jetPt"}
    reco_trees:
      # MET
      - trackerMET
      - puppiMETEt
      # HT
      - trackerHT
      - phase1PuppiHT
      - caloJetHT
      # Jet
      - seededConePuppiJetPt
      - seededConePuppiJetEta
      - trackerJetPt
      - trackerJetEta
      - phase1PuppiJetPt
      - phase1PuppiJetEta
  VBFHToTauTau: "/eos/cms/store/cmst3/group/l1tr/phase2Menu/EmuDev/VBFHToTauTau_M125_14TeV_powheg_pythia8_correctedGridpack_tuneCP5/VBFToTauTau_PU200_v22/220407_095503/0000//"
  GluGluToGG: "/eos/cms/store/cmst3/group/l1tr/phase2Menu/EmuDev/GluGluHToGG_M125_14TeV_powheg_pythia8_TuneCP5/HGG_PU200_v22/220407_094856/0000//"
  GluGluToHHTo2B2Tau: "/eos/cms/store/cmst3/group/l1tr/phase2Menu/EmuDev/GluGluToHHTo2B2Tau_node_SM_TuneCP5_14TeV-madgraph-pythia8/GGToHHTo2B2Tau_PU200_v22/220408_073133/0000//"
