ArbitraryPlotName:
  inputs:
    version: "V22"
    sample: "TT"
  object_keys: ["trackerMET", "puppiMETEt"]
  truth_key: "genMetTrue"
  plot_labels: ["Tracker MET", "Puppi MET"]
  threshold: 70
  xlabel: "MET (GeV)"
  ylabel: "Efficiency with 70 GeV Threshold"
  binning:
    min: 0
    max: 500 
    step: 20
