caloJet:
  sample: TT
  match_dR: 0.3
  label: "Calo Jet"
  eta_ranges:
    range0: [0, 7]
  cuts:
    range0:
      - "abs({eta}) < 7"
  ids:
    default:
      cuts:
        range0:
          - "abs({eta}) < 7"

phase1PuppiJet:
  sample: TT
  match_dR: 0.3
  label: "Histogrammed PuppiJet"
  eta_ranges:
    range0: [0, 7]
  ids:
    default:
      cuts:
        range0:
          - "abs({eta}) < 7"

seededConePuppiJet:
  sample: TT
  match_dR: 0.35
  label: "Seeded Cone PuppiJet"
  eta_ranges:
    range0: [0, 7]
  ids:
    default:
      cuts:
        range0:
          - "abs({eta}) < 7"

trackerJet:
  sample: TT
  match_dR: 0.4
  label: "Tracker Jet"
  eta_ranges:
    range0: [0, 7]
  ids:
    default:
      cuts:
        range0:
          - "abs({eta}) < 7"
