gmtMuon:
  label: "GMT Muon"
  match_dR: 0.3
  eta_ranges:
    inclusive: [0, 5]
    barrel: [0, 0.83]
    overlap: [0.83, 1.24]
    endcap: [1.24, 2.4]
  ids:
    default: {}

gmtTkMuon:
  label: "GMT TkMuon"
  match_dR: 0.1
  eta_ranges:
    inclusive: [0, 5]
    barrel: [0, 0.83]
    overlap: [0.83, 1.24]
    endcap: [1.24, 2.4]
  cuts:
    inclusive:
      - "{quality} > 0"
  ids:
    default:
      cuts:
        inclusive:
          - "{quality} > 0"
