gmtMuon:
  label: "GMT Muon"
  match_dR: 0.3
  eta_ranges:
    range0: [0, 5]
  ids:
    default: {}
    barrel:
      cuts:
        range0:
          - "abs({eta}) < 0.83"
    overlap:
      cuts:
        range0:
          - "abs({eta}) > 0.83"
          - "abs({eta}) < 1.24"
    endcap:
      cuts:
        range0:
          - "abs({eta}) > 1.24"
          - "abs({eta}) < 2.4"


gmtTkMuon:
  label: "GMT TkMuon"
  match_dR: 0.1
  eta_ranges:
    range0: [0, 5]
  cuts:
    range0:
      - "{quality} > 0"
  ids:
    default: {}
    barrel:
      cuts:
        range0:
          - "abs({eta}) < 0.83"
          - "{quality} > 0"
    overlap:
      cuts:
        range0:
          - "abs({eta}) > 0.83"
          - "abs({eta}) < 1.24"
          - "{quality} > 0"
    endcap:
      cuts:
        range0:
          - "abs({eta}) > 1.24"
          - "abs({eta}) < 2.4"
          - "{quality} > 0"
