nnTau:
  label: "NN Tau"
  match_dR: 0.1
  eta_ranges:
    range0: [0, 5]
  cuts:
    range0:
      - "abs({eta}) < 2.4"
      - "{passloosenn}==1"
  ids:
    default: {}

caloTau:
  label: "Calo Tau"
  match_dR: 0.3
  eta_ranges:
    range0: [0, 5]
  cuts:
    range0:
      - "abs({eta}) < 2.4"
  ids:
    default: {}
