V22_V29_13X_GMTMuonsBarrel_Comparison:
  files:
    MuonsTrigger_20_V22:
      object: gmtMuon
      dir: outputs/V22/turnons/
      label: "GMT Muon (V22)"
    MuonsTrigger_20_V29_13X:
      object: gmtMuon
      dir: outputs/V29_13X/turnons/
      label: "GMT Muon (V29_13X)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  watermark: "V22_V29_13X_gmtMuonBarrel_Comp"
  save_dir: "outputs/V22vs27/turnons"

V22_V29_13X_ElectronsBarrel_Comparison:
  files:
    ElectronsTriggerBarrel_30_V22:
      object: tkElectron
      dir: outputs/V22/turnons/
      label: "tkElectron (V22)"
    ElectronsTriggerBarrel_30_V29_13X:
      object: tkElectron
      dir: outputs/V29_13X/turnons/
      label: "tkElectron (V29_13X)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  watermark: "V22_V29_13X_EGBarrel_Comp"
  save_dir: "outputs/V22vs27/turnons"

V22_V29_13X_GMTtkMuonsBarrel_Comparison:
  files:
    MuonsTrigger_20_V22:
      object: gmtMuon
      dir: outputs/V22/turnons/
      label: "GMT tkMuon (V22)"
    MuonsTrigger_20_V29_13X:
      object: gmtMuon
      dir: outputs/V29_13X/turnons/
      label: "GMT tkMuon (V29_13X)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  watermark: "V22_V29_13X_gmtTkMuonBarrel_Comp"
  save_dir: "outputs/V22vs27/turnons"
