HTRates:
  sample: MinBias
  version: V29
  test_objects:
    - phase1PuppiHT:default
    - seededConePuppiHT:default
    - trackerHT:default
  binning:
    min: 50
    max: 975
    step: 25

MuonRates:
  sample: MinBias
  version: V29
  test_objects:
    - gmtMuon:default
    - gmtTkMuon:default
  binning:
    min: 0
    max: 75
    step: 3

JetDefaultRates:
  sample: MinBias
  version: V29
  test_objects:
    - phase1PuppiJet:default
    - seededConePuppiJet:default
    - trackerJet:default
  binning:
    min: 40
    max: 420
    step: 20

EGRates:
  sample: MinBias
  version: V29
  test_objects:
    - EG:default
    - tkElectron:NoIso
    - tkElectron:Iso
    - tkPhoton:Iso
  binning:
    min: 10
    max: 97
    step: 3

TauRates:
  sample: MinBias
  version: V29
  test_objects:
    - nnTau:default
    - caloTau:default
  binning:
    min: 10
    max: 155
    step: 5
