V22_V27_GMTMuonsBarrel_Comparison:
  files:
    MuonsTrigger_20_V22:
      object: gmtMuon
      dir: outputs/V22/turnons/
      label: "GMT Muon (V22)"
    MuonsTrigger_20_V27:
      object: gmtMuon
      dir: outputs/V27/turnons/
      label: "GMT Muon (V27)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  watermark: "V22_V27_gmtMuonBarrel_Comp"
  save_dir: "outputs/V22vs27/turnons"

V22_V27_ElectronsBarrel_Comparison:
  files:
    ElectronsTriggerBarrel_30_V22:
      object: tkElectron
      dir: outputs/V22/turnons/
      label: "tkElectron (V22)"
    ElectronsTriggerBarrel_30_V27:
      object: tkElectron
      dir: outputs/V27/turnons/
      label: "tkElectron (V27)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  watermark: "V22_V27_EGBarrel_Comp"
  save_dir: "outputs/V22vs27/turnons"

V22_V27_GMTtkMuonsBarrel_Comparison:
  files:
    MuonsTrigger_20_V22:
      object: gmtMuon
      dir: outputs/V22/turnons/
      label: "GMT tkMuon (V22)"
    MuonsTrigger_20_V27:
      object: gmtMuon
      dir: outputs/V27/turnons/
      label: "GMT tkMuon (V27)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  watermark: "V22_V27_gmtTkMuonBarrel_Comp"
  save_dir: "outputs/V22vs27/turnons"
