JetTurnonBarrel:
  sample: TT
  default_version: V27
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    caloJet:
      match_dR: 0.3
      suffix: "Pt"
      label: "Calo Jet"
      cuts:
        - "abs({eta}) < 2.5"
    phase1PuppiJet:
      match_dR: 0.3
      suffix: "Pt"
      label: "Histogrammed PuppiJet"
      cuts:
        - "abs({eta}) < 2.4"
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Pt"
      label: "Seeded Cone PuppiJet"
      cuts:
        - "abs({eta}) < 2.4"
    trackerJet:
      match_dR: 0.4
      suffix: "Pt"
      label: "Tracker Jet"
      cuts:
        - "abs({eta}) < 2.4"
  thresholds: [50,100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, barrel)"
  binning:
    min: 0
    max: 700
    step: 10

JetTurnonEndcap:
  sample: TT
  default_version: V27
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    caloJet:
      match_dR: 0.3
      suffix: "Pt"
      label: "Calo Jet"
      cuts:
        - "abs({eta}) < 5"
    phase1PuppiJet:
      match_dR: 0.3
      suffix: "Pt"
      label: "Histogrammed PuppiJet"
      cuts:
        - "abs({eta}) < 2.4"
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Pt"
      label: "Seeded Cone PuppiJet"
      cuts:
        - "abs({eta}) < 2.4"
    trackerJet:
      match_dR: 0.4
      suffix: "Pt"
      label: "Tracker Jet"
      cuts:
        - "abs({eta}) < 2.4"
  thresholds: [50]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, endcap)"
  binning:
    min: 0
    max: 900
    step: 20

JetTurnonForward:
  sample: TT
  default_version: V27
  reference_object:
    object: "jet"
    suffix: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 2.4"
      object:
        - "abs({eta}) < 5"
  test_objects:
    caloJet:
      match_dR: 0.3
      suffix: "Pt"
      label: "Calo Jet"
      cuts:
        - "abs({eta}) < 5"
    phase1PuppiJet:
      match_dR: 0.3
      suffix: "Pt"
      label: "Histogrammed PuppiJet"
      cuts:
        - "abs({eta}) < 5"
    seededConePuppiJet:
      match_dR: 0.35
      suffix: "Pt"
      label: "Seeded Cone PuppiJet"
      cuts:
        - "abs({eta}) < 5"
  thresholds: [50,100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, forward)"
  binning:
    min: 0
    max: 700
    step: 10
