PhotonsMatching_Eta_Pt10to25:
  sample: Hgg
  default_version: V27
  reference_object:
    object: "part_gamma"
    suffix: "Eta"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} < 25"
        - "{pt} > 10"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    EG:
      suffix: "Eta"
      label: "EG Photon"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 3"
        #- "{passeseleid} == 1"
    tkPhoton:
      match_dR: 0.15
      suffix: "Eta"
      label: "tkPhoton"
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 3.0"
        #- "({quality} // 4) == 1"
        #- "{passeseleid} == 1"
    tkIsoPhoton:
      base_obj: "tkPhoton"
      match_dR: 0.15
      suffix: "Eta"
      label: "tkIsoPhoton"
      iso_EE: 0.2
      iso_BB: 0.2
      iso_branch: trkiso
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 3.0"
        #- "{passeseleid} == 1"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($10 < p_T < 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

PhotonsMatching_Eta_Pt25:
  sample: Hgg
  default_version: V27
  reference_object:
    object: "part_gamma"
    suffix: "Eta"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} >= 25"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    EG:
      suffix: "Eta"
      label: "EG EleID"
      match_dR: 0.2
      quality_id: "QUAL_125x_EGID"
      cuts:
        - "abs({eta}) < 3"
        - "{passeseleid} == 1"
    tkPhoton:
      match_dR: 0.15
      suffix: "Eta"
      label: "tkPhoton"
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 3.0"
        #- "{passeseleid} == 1"
    tkIsoPhoton:
      base_obj: "tkPhoton"
      match_dR: 0.15
      suffix: "Eta"
      label: "tkIsoPhoton"
      iso_EE: 0.2
      iso_BB: 0.2
      iso_branch: trkiso
      quality_id: "QUAL_125x_tkPhoID"
      cuts:
        - "abs({eta}) < 3.0"
        #- "{passeseleid} == 1"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($10 < p_T < 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2
