MHT_150_V22:
  files:
    MHT30_150:
      object: trackerMHT
      dir: outputs/V22/turnons/
    MHT15_150:
      object: phase1PuppiMHT
      dir: outputs/V22/turnons/
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  watermark: "V22_MHTBarrel"
  save_dir: "outputs/V22/turnons"