V22_V26_ElectronsBarrel_Comparison:
  files:
    ElectronsTriggerBarrel_30_V22:
      object: tkElectron
      dir: outputs/V22/turnons/
      label: "tkElectron (V22)"
    ElectronsTriggerBarrel_30_V26:
      object: tkElectron
      dir: outputs/V26/turnons/
      label: "tkElectron (V26)"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Matching Efficiency (Barrel)"
  watermark: "V22_V26_EGBarrel_Comp"
  save_dir: "outputs/V22/turnons"