# part_e:
#   label: "Gen Electron"
#   eta_ranges:
#     inclusive: [0, 7]
#   ids:
#     gen_electron_default:
#       cuts:
#         inclusive:
#           - "{dr_0.3} < 0.15"
GenPart:
  label: "Gen Electron"
  eta_ranges:
    inclusive: [0, 7]
  ids:
    gen_electron_default:
      cuts:
        inclusive:
          - "(({statusFlags}>>7)&1) == 1"

L1tkElectron:
  match_dR: 0.15
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.479]
    endcap: [1.479, 5]
  ids:
    NoIso:
      label: "TkElectron"
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
          - "({eleId} == 1) | ({pt} < 25)"
    NoIsoForIso:
      # This id is exclusively used for the
      # isoloation wp derivation
      label: "TkElectron id in barrel"
      cuts:
        inclusive:
          - "abs({eta}) < 2.7"
        barrel:
          - "({eleId} == 1) | ({pt} < 25)"
    Iso:
      label: "TkIsoElectron"
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
        barrel:
          - "abs({relIso}) < 0.13"
          - "({eleId} == 1) | ({pt} < 25)"
        endcap:
          - "abs({relIso}) < 0.28"
    IsoNoIDinEE:
      label: "TkIsoElectron"
      cuts:
        inclusive:
          - "abs({eta}) < 2.4"
        barrel:
          - "abs({relIso}) < 0.13"
          - "({eleId} == 1) | ({pt} < 25)"
        endcap:
          - "abs({relIso}) < 0.28"

L1EG:
  match_dR: 0.2
  eta_ranges:
    inclusive: [0, 7]
    barrel: [0, 1.479]
    endcap: [1.479, 3.0]
  label: "EG"
  ids:
    default:
      cuts:
        inclusive:
          - "abs({eta}) < 3.0"
          - "{pt} > 5" 
        barrel:
          - "{eleId} == 1"
        endcap:
          - "{saId} == 1"
