JetMatchingForward_3p7to7:
  version: V29
  match_test_to_ref: True
  reference_object:
    object: "jet"
    sample: TT
    x_arg: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 3.7"
      object:
        - "abs({eta}) < 5"
  test_objects:
    caloJet-default: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, forward)"
  binning:
    min: 0
    max: 300
    step: 5

JetMatchingBarrel:
  version: V29
  match_test_to_ref: True
  reference_object:
    object: "jet"
    sample: TT
    x_arg: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    phase1PuppiJet-barrel: "Pt"
    seededConePuppiJet-barrel: "Pt"
    trackerJet-barrel: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, barrel)"
  binning:
    min: 0
    max: 500
    step: 10

JetMatchingEndcap:
  version: V29
  match_test_to_ref: True
  reference_object:
    object: "jet"
    sample: TT
    x_arg: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    phase1PuppiJet-barrel: "Pt"
    seededConePuppiJet-barrel: "Pt"
    trackerJet-barrel: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, endcap)"
  binning:
    min: 0
    max: 500
    step: 10

JetMatchingForward:
  version: V29
  match_test_to_ref: True
  reference_object:
    object: "jet"
    sample: TT
    x_arg: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 2.4"
      object:
        - "abs({eta}) < 5"
  test_objects:
    phase1PuppiJet-forward: "Pt"
    seededConePuppiJet-forward: "Pt"
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, forward)"
  binning:
    min: 0
    max: 500
    step: 10
