JetTurnonBarrel:
  version: V29
  match_test_to_ref: True
  reference_object:
    object: "jet"
    sample: TT
    x_arg: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    phase1PuppiJet-barrel: "Pt"
    seededConePuppiJet-barrel: "Pt"
    trackerJet-barrel: "Pt"
  thresholds: [50,100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, barrel)"
  binning:
    min: 0
    max: 500
    step: 10

JetTurnonEndcap:
  version: V29
  match_test_to_ref: True
  reference_object:
    object: "jet"
    sample: TT
    x_arg: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    phase1PuppiJet-barrel: "Pt"
    seededConePuppiJet-barrel: "Pt"
    trackerJet-barrel: "Pt"
  thresholds: [50]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, endcap)"
  binning:
    min: 0
    max: 500
    step: 10

JetTurnonForward:
  version: V29
  match_test_to_ref: True
  reference_object:
    sample: TT
    object: "jet"
    x_arg: "Pt"
    label: "Gen Jets"
    cuts:
      event:
        - "abs({eta}) > 2.4"
      object:
        - "abs({eta}) < 5"
  test_objects:
    phase1PuppiJet-forward: "Pt"
    seededConePuppiJet-forward: "Pt"
  thresholds: [50,100]
  scalings:
    method: "naive"
    threshold: 0.95
  xlabel: "Gen. $p_T$ (GeV)"
  ylabel: "Trigger Efficiency (<threshold> GeV, forward)"
  binning:
    min: 0
    max: 500
    step: 10
