ElectronsIsolation:
  sample: DYLL_M50
  default_version: V28
  iso_vs_efficiency: True
  reference_object:
    object: "part_e"
    suffix: "Pt"
    label: "Gen Electrons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 2.4"
  test_objects:
    tkElectron:
      suffix: "trkiso"
      label: "TkElectron"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 2.4"
        - "{passeseleid} == 1"
  xlabel: "Isolation"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 0.5
    step: 0.005

