PhotonsMatching_Eta_Pt25_PassSa_NOPhoID_iso0p2:
  sample: Hgg
  default_version: V28
  reference_object:
    object: "part_gamma"
    suffix: "Eta"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} > 25"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    tkPhoton:
      match_dR: 0.15
      suffix: "Eta"
      label: "TkPhoton NO PhoID"
      iso_EE: 0.2
      iso_BB: 0.2
      iso_branch: trkiso
      #quality_id: "QUAL_TkPho"
      cuts:
        - "abs({eta}) < 3.0"
      #  - "{passesphoid} == 1"
    EG:
      suffix: "Eta"
      label: "EG SaID"
      match_dR: 0.2
      #quality_id: "QUAL_EG"
      cuts:
        - "abs({eta}) < 3"
        - "{passessaid} == 1"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($p_T > 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

PhotonsMatching_Eta_Pt15to25_PassEleID_iso0p2:
  sample: Hgg
  default_version: V28
  reference_object:
    object: "part_gamma"
    suffix: "Eta"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} > 15"
        - "{pt} < 25"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    tkPhoton:
      match_dR: 0.15
      suffix: "Eta"
      label: "TkPhoton EleID"
      iso_EE: 0.2
      iso_BB: 0.2
      iso_branch: trkiso
      #quality_id: "QUAL_TkPho"
      cuts:
        - "abs({eta}) < 3.0"
        - "{passeseleid} == 1"
    EG:
      suffix: "Eta"
      label: "EG EleID"
      match_dR: 0.2
      #quality_id: "QUAL_EG"
      cuts:
        - "abs({eta}) < 3"
        - "{passeseleid} == 1"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($15 < p_T < 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

PhotonsMatching_Eta_Pt25_PassEleID_iso0p2:
  sample: Hgg
  default_version: V28
  reference_object:
    object: "part_gamma"
    suffix: "Eta"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} > 25"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    tkPhoton:
      match_dR: 0.15
      suffix: "Eta"
      label: "TkPhoton EleID"
      iso_EE: 0.2
      iso_BB: 0.2
      iso_branch: trkiso
      #quality_id: "QUAL_TkPho"
      cuts:
        - "abs({eta}) < 3.0"
        - "{passeseleid} == 1"
    EG:
      suffix: "Eta"
      label: "EG EleID"
      match_dR: 0.2
      #quality_id: "QUAL_EG"
      cuts:
        - "abs({eta}) < 3"
        - "{passeseleid} == 1"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($p_T > 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

PhotonsMatching_Eta_Pt25_PassSa_PhoID_iso0p2:
  sample: Hgg
  default_version: V28
  reference_object:
    object: "part_gamma"
    suffix: "Eta"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "{pt} > 25"
      object:
        - "abs({eta}) < 3.0"
  test_objects:
    tkPhoton:
      match_dR: 0.15
      suffix: "Eta"
      label: "TkPhoton PhoID"
      iso_EE: 0.2
      iso_BB: 0.2
      iso_branch: trkiso
      #quality_id: "QUAL_TkPho"
      cuts:
        - "abs({eta}) < 3.0"
        - "{passesphoid} == 1"
    EG:
      suffix: "Eta"
      label: "EG SaID"
      match_dR: 0.2
      #quality_id: "QUAL_EG"
      cuts:
        - "abs({eta}) < 3"
        - "{passessaid} == 1"
  xlabel: "Gen. $\\eta$"
  ylabel: "Matching Efficiency ($p_T > 25$ GeV)"
  binning:
    min: -3
    max: 3
    step: 0.2

