PhotonIsolation_Barrel:
  sample: Hgg
  default_version: V28
  iso_vs_efficiency: True
  reference_object:
    object: "part_gamma"
    suffix: "Pt"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) < 1.5"
      object:
        - "abs({eta}) < 1.5"
  test_objects:
    tkPhoton:
      suffix: "trkiso"
      label: "TkPhoton"
      match_dR: 0.15
      cuts:
        - "abs({eta}) < 1.5"
        - "{passesphoid} == 1"
  xlabel: "Isolation"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 0.5
    step: 0.005

PhotonIsolation_Endcap:
  sample: Hgg
  default_version: V28
  iso_vs_efficiency: True
  reference_object:
    object: "part_gamma"
    suffix: "Pt"
    label: "Gen Photons"
    cuts:
      event:
        - "{dr_0.3} < 0.15"
        - "abs({eta}) > 1.5"
      object:
        - "abs({eta}) > 1.5"
  test_objects:
    tkPhoton:
      suffix: "trkiso"
      label: "TkPhoton"
      match_dR: 0.15
      cuts:
        - "abs({eta}) > 1.5"
        - "{passesphoid} == 1"
  xlabel: "Isolation"
  ylabel: "Efficiency"
  binning:
    min: 0
    max: 0.5
    step: 0.005

